version: "3.3"
services: 
  app:
    build: web
    image: tree-app
    ports:
      - 3000:3000
  db: 
    build: db
    image: trees-db
    volumes: 
      - tree-data:/var/lib/postgresql/data
    ports: 
      - 5432:5432
volumes:
  tree-data:

